spring:
  application:
    name: wechatshop-order

# 本模块版本号
wechatshop:
  order:
    version: 1.0.0

dubbo:
  registry:
    # zookeeper 注册中心地址
    address: zookeeper://127.0.0.1:2181

  scan:
    base-packages: com.catmmao.wechatshop.orderService.service

server:
  port: 8081