spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

# 本模块版本号
wechatshop:
  order:
    version: 1.0.0

dubbo:
  registry:
    # zookeeper 注册中心地址
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.catmmao.wechatshop.orderService.service

server:
  port: 8081

mybatis:
  config-location: classpath:db/mybatis/config.xml
