CREATE TABLE order_goods_mapping
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    GOODS_ID   BIGINT,
    ORDER_ID   BIGINT,
    NUMBER     BIGINT, -- 单位 分
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP ON UPDATE NOW()
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

INSERT INTO order_goods_mapping(ID, GOODS_ID, ORDER_ID, NUMBER)
VALUES (1, 1, 1, 5),
       (2, 2, 1, 9);
